name: Generate craft.sh
on:
  push:
    branches: [ "master" ]
    paths:
      - 'sources/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'sources/**'

jobs:
  generateCraftSh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Craft glue craft.sh
        run: |
          bash sources/craft.sh --overwrite --glue craft.sh sources/header sources/common.sh sources/glue_mode.sh sources/split_mode.sh sources/craft.sh
          chmod +x craft.sh

      - name: Commit and push the new craft.sh
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Auto update craft.sh'
          add: 'craft.sh'
          pathspec_error_handling: exitImmediately
